//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pchp.CodeAnalysis {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PhpResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal PhpResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peachpie.CodeAnalysis.PhpResources", typeof(PhpResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Peachpie HELP..
        /// </summary>
        public static string IDS_Help {
            get {
                return ResourceManager.GetString("IDS_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Peachpie PHP Compiler..
        /// </summary>
        public static string IDS_Logo {
            get {
                return ResourceManager.GetString("IDS_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Peachpie PHP Compiler.
        /// </summary>
        public static string IDS_ToolName {
            get {
                return ResourceManager.GetString("IDS_ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A reference to the current runtime context..
        /// </summary>
        public static string XmlDoc_ContextParamDescription {
            get {
                return ResourceManager.GetString("XmlDoc_ContextParamDescription", resourceCulture);
            }
        }
    }
}
