//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pchp.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pchp.Library.Resources.DateResources", typeof(DateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A textual day could not be found.
        /// </summary>
        internal static string day_notfound {
            get {
                return ResourceManager.GetString("day_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string.
        /// </summary>
        internal static string empty_string {
            get {
                return ResourceManager.GetString("empty_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escaped character expected.
        /// </summary>
        internal static string esc_char_expected {
            get {
                return ResourceManager.GetString("esc_char_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The escaped character could not be found.
        /// </summary>
        internal static string esc_char_notfound {
            get {
                return ResourceManager.GetString("esc_char_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A four digit year could not be found.
        /// </summary>
        internal static string four_digit_year_notfound {
            get {
                return ResourceManager.GetString("four_digit_year_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour can not be higher than 12.
        /// </summary>
        internal static string hour_gt_12 {
            get {
                return ResourceManager.GetString("hour_gt_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meridian can only come after an hour has been found.
        /// </summary>
        internal static string meridian_missing_hour {
            get {
                return ResourceManager.GetString("meridian_missing_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A meridian could not be found.
        /// </summary>
        internal static string meridian_notfound {
            get {
                return ResourceManager.GetString("meridian_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A textual month could not be found.
        /// </summary>
        internal static string month_notfound {
            get {
                return ResourceManager.GetString("month_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The separation symbol ({0}) could not be found.
        /// </summary>
        internal static string separation_notfound {
            get {
                return ResourceManager.GetString("separation_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format separator does not match.
        /// </summary>
        internal static string separator_does_not_match {
            get {
                return ResourceManager.GetString("separator_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A six digit millisecond could not be found.
        /// </summary>
        internal static string six_digit_ms_notfound {
            get {
                return ResourceManager.GetString("six_digit_ms_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A three digit day-of-year could not be found.
        /// </summary>
        internal static string three_digit_doy_notfound {
            get {
                return ResourceManager.GetString("three_digit_doy_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing data.
        /// </summary>
        internal static string trailing_data {
            get {
                return ResourceManager.GetString("trailing_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two digit day could not be found.
        /// </summary>
        internal static string two_digit_day_notfound {
            get {
                return ResourceManager.GetString("two_digit_day_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two digit hour could not be found.
        /// </summary>
        internal static string two_digit_hour_notfound {
            get {
                return ResourceManager.GetString("two_digit_hour_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two digit minute could not be found.
        /// </summary>
        internal static string two_digit_min_notfound {
            get {
                return ResourceManager.GetString("two_digit_min_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two digit month could not be found.
        /// </summary>
        internal static string two_digit_month_notfound {
            get {
                return ResourceManager.GetString("two_digit_month_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two digit second could not be found.
        /// </summary>
        internal static string two_digit_sec_notfound {
            get {
                return ResourceManager.GetString("two_digit_sec_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two digit year could not be found.
        /// </summary>
        internal static string two_digit_year_notfound {
            get {
                return ResourceManager.GetString("two_digit_year_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timezone could not be found in the database.
        /// </summary>
        internal static string tz_notfound {
            get {
                return ResourceManager.GetString("tz_notfound", resourceCulture);
            }
        }
    }
}
