//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pchp.Library.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal InfoResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peachpie.Library.Resources.InfoResources", typeof(InfoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Peachpie logo.
        /// </summary>
        public static string LogoAlt {
            get {
                return ResourceManager.GetString("LogoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to http://www.peachpie.io/.
        /// </summary>
        public static string LogoHref {
            get {
                return ResourceManager.GetString("LogoHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJgAAAAmCAYAAAA4AlIkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsSAAALEgHS3X78AAARxUlEQVR42u2ba3AU15XH/+fc24/pGT1GIKERIAlhb7zrOFtEmJQfSeyRZJyAbTAMBtuYZGMrm7jWzqZ2A5s4W5XdxEHZR9aVLUlgg+MQHpYwmGBAmMFOso69G1u1eSdl0IOAcGyTDA+9Zrr73v0wAiQxkkZyjJxa/ar0QXe6T597+n8f53Q3MMUUU0zxpwqN94SGaMk1TPiQZHq/ZMxkohABrgbeVlr/Umm85ind+kD8ZM9kd26KyScrgdVHIyEmWm0yfcKWtMCRjIAkmIK6DaY+AkwAeb4GUr5Gn6eO93n6u32+enzNwa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LogoSrc {
            get {
                return ResourceManager.GetString("LogoSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  body {background-color: #fff; color: #222; font-family: sans-serif;}
        ///pre {margin: 0; font-family: monospace;}
        ///a:link {color: #009; text-decoration: none; background-color: #fff;}
        ///a:hover {text-decoration: underline;}
        ///table {border-collapse: collapse; border: 0; width: 934px; box-shadow: 1px 2px 3px #ccc;}
        ///.center {text-align: center;}
        ///.center table {margin: 1em auto; text-align: left;}
        ///.center th {text-align: center !important;}
        ///td, th {border: 1px solid #666; font-size: 75%; vertical-align: baselin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
    }
}
