//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pchp.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peachpie.Library.Resources.InfoResources", typeof(InfoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeachPie PHP Compiler for .NET.
        /// </summary>
        internal static string LogoAlt {
            get {
                return ResourceManager.GetString("LogoAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.peachpie.io/.
        /// </summary>
        internal static string LogoHref {
            get {
                return ResourceManager.GetString("LogoHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEQAAABECAYAAAA4E5OyAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsRAAALEQF/ZF+RAAAABmJLR0QA/wD/AP+gvaeTAAAP2klEQVR4Xu1bC3RV1Zn+zjn3lZsEMAkveSr4BMHiaBWhM6Ot9Vkf47QqVcciIxW0IzBWizPFDg7GAa1odYqdDq4W7SAyo7VLO+o4ilABFR8o6PAUE8IjIZDkPs9jvv/sfUluchNukhvBhd9aJzfnP+fus/e3/+fe5xpNVx3vea4NwOBxNMODYQZgNF053IPrkI+jnBDPA0wL5kHFEEKO5sPngJyo/75CBl8R0gp0qvQhDn2I2QPciF1m1FHguVpEt5VMAokY4KT0RYLXEAgCkWKYoTA8/V3DyN03N9bA79swS3rzpm7233 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogoSrc {
            get {
                return ResourceManager.GetString("LogoSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///body {background-color: #fff; color: #222; font-family: sans-serif;}
        ///pre {margin: 0; font-family: monospace;}
        ///a:link {color: #009; text-decoration: none; background-color: #fff;}
        ///a:hover {text-decoration: underline;}
        ///table {border-collapse: collapse; border: 0; width: 934px; box-shadow: 1px 2px 3px #ccc;}
        ///.center {text-align: center;}
        ///.center table {margin: 1em auto; text-align: left;}
        ///.center th {text-align: center !important;}
        ///td, th {border: 1px solid #666; font-size: 75% [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
    }
}
