//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pchp.Library.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peachpie.Library.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Additional parameters not supported.
        /// </summary>
        public static string additional_parameters_not_supported {
            get {
                return ResourceManager.GetString("additional_parameters_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; should not be empty.
        /// </summary>
        public static string arg_empty {
            get {
                return ResourceManager.GetString("arg_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument &apos;{0}&apos; has invalid length.
        /// </summary>
        public static string arg_invalid_length {
            get {
                return ResourceManager.GetString("arg_invalid_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value &apos;{1}&apos; is invalid for argument &apos;{0}&apos;.
        /// </summary>
        public static string arg_invalid_value {
            get {
                return ResourceManager.GetString("arg_invalid_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; should not be negative.
        /// </summary>
        public static string arg_negative {
            get {
                return ResourceManager.GetString("arg_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; should be positive.
        /// </summary>
        public static string arg_negative_or_zero {
            get {
                return ResourceManager.GetString("arg_negative_or_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; not an object or class name.
        /// </summary>
        public static string arg_not_object_or_class_name {
            get {
                return ResourceManager.GetString("arg_not_object_or_class_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; should not be null nor empty.
        /// </summary>
        public static string arg_null_or_empty {
            get {
                return ResourceManager.GetString("arg_null_or_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; is out of bounds.
        /// </summary>
        public static string arg_out_of_bounds {
            get {
                return ResourceManager.GetString("arg_out_of_bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; should not be zero.
        /// </summary>
        public static string arg_zero {
            get {
                return ResourceManager.GetString("arg_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument #{0} should be an array.
        /// </summary>
        public static string argument_not_array {
            get {
                return ResourceManager.GetString("argument_not_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument #{0} should be an array or a sort flag.
        /// </summary>
        public static string argument_not_array_or_sort_flag {
            get {
                return ResourceManager.GetString("argument_not_array_or_sort_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument &apos;{0}&apos; must be an integer indexed array.
        /// </summary>
        public static string argument_not_integer_indexed_array {
            get {
                return ResourceManager.GetString("argument_not_integer_indexed_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Second argument is not an object or class name.
        /// </summary>
        public static string argument_not_object_or_class_name {
            get {
                return ResourceManager.GetString("argument_not_object_or_class_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to By changing ASP.NET session ID, all the session data created during this request will be lost. New session will start in the next request..
        /// </summary>
        public static string aspnet_sessionhandler_id_reset {
            get {
                return ResourceManager.GetString("aspnet_sessionhandler_id_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: &apos;*&apos; ignored.
        /// </summary>
        public static string asterisk_ignored {
            get {
                return ResourceManager.GetString("asterisk_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attempted {0} variable override.
        /// </summary>
        public static string attempted_variable_override {
            get {
                return ResourceManager.GetString("attempted_variable_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Collating element representing more than one character cannot be the first endpoint of range.
        /// </summary>
        public static string bad_collating_el_at_first_endpoint_of_range {
            get {
                return ResourceManager.GetString("bad_collating_el_at_first_endpoint_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: binary data length has overflown integer size.
        /// </summary>
        public static string binary_data_overflown {
            get {
                return ResourceManager.GetString("binary_data_overflown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string both_must_be_arrays_or_nonarrays {
            get {
                return ResourceManager.GetString("both_must_be_arrays_or_nonarrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This function is deprecated, use the call_user_func variety with the array(&amp;$obj, &quot;method&quot;) syntax instead.
        /// </summary>
        public static string call_user_method_deprecated {
            get {
                return ResourceManager.GetString("call_user_method_deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot open connection: {0}.
        /// </summary>
        public static string cannot_open_connection {
            get {
                return ResourceManager.GetString("cannot_open_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot retrieve schema information.
        /// </summary>
        public static string cannot_retrieve_schema {
            get {
                return ResourceManager.GetString("cannot_retrieve_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot send the mail due to error: &apos;{0}&apos;.
        /// </summary>
        public static string cannot_send_email {
            get {
                return ResourceManager.GetString("cannot_send_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid &apos;{0}&apos;-range, no character to the left of &apos;{0}&apos;.
        /// </summary>
        public static string char_range_no_char_on_left {
            get {
                return ResourceManager.GetString("char_range_no_char_on_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid &apos;{0}&apos;-range, no character to the right of &apos;{0}&apos;.
        /// </summary>
        public static string char_range_no_char_on_right {
            get {
                return ResourceManager.GetString("char_range_no_char_on_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid &apos;{0}&apos;-range, &apos;{0}&apos;-range needs to be incrementing.
        /// </summary>
        public static string char_range_not_incrementing {
            get {
                return ResourceManager.GetString("char_range_not_incrementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Character class cannot be an endpoint of range (second endpoint here).
        /// </summary>
        public static string character_class_at_second_endpoint_of_range {
            get {
                return ResourceManager.GetString("character_class_at_second_endpoint_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Class {0} has no unserializer.
        /// </summary>
        public static string class_has_no_unserializer {
            get {
                return ResourceManager.GetString("class_has_no_unserializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to instantiate class &apos;{0}&apos;..
        /// </summary>
        public static string class_instantiation_failed {
            get {
                return ResourceManager.GetString("class_instantiation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Command execution failed: {0}.
        /// </summary>
        public static string command_execution_failed {
            get {
                return ResourceManager.GetString("command_execution_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of connections reached the limit ({0}).
        /// </summary>
        public static string connection_limit_reached {
            get {
                return ResourceManager.GetString("connection_limit_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t force cut when width is zero.
        /// </summary>
        public static string cut_forced_with_zero_width {
            get {
                return ResourceManager.GetString("cut_forced_with_zero_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Database selection failed: {0}.
        /// </summary>
        public static string database_selection_failed {
            get {
                return ResourceManager.GetString("database_selection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delimiter must not be alphanumeric or backslash.
        /// </summary>
        public static string delimiter_alnum_backslash {
            get {
                return ResourceManager.GetString("delimiter_alnum_backslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid mode for descriptor item #{0}.
        /// </summary>
        public static string descriptor_item_invalid_mode {
            get {
                return ResourceManager.GetString("descriptor_item_invalid_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Missing file name parameter from descriptor item #{0}.
        /// </summary>
        public static string descriptor_item_missing_file_name {
            get {
                return ResourceManager.GetString("descriptor_item_missing_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Missing mode parameter from descriptor item #{0}.
        /// </summary>
        public static string descriptor_item_missing_mode {
            get {
                return ResourceManager.GetString("descriptor_item_missing_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Descriptor item #{0} should contain handle qualifier and parameters.
        /// </summary>
        public static string descriptor_item_missing_qualifier {
            get {
                return ResourceManager.GetString("descriptor_item_missing_qualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Descriptor item #{0} must be either an array or a resource.
        /// </summary>
        public static string descriptor_item_not_array_nor_resource {
            get {
                return ResourceManager.GetString("descriptor_item_not_array_nor_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Descriptor #{0} is not supported.
        /// </summary>
        public static string descriptor_unsupported {
            get {
                return ResourceManager.GetString("descriptor_unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Deserialization failed: {0} at offset {1} of {2} bytes.
        /// </summary>
        public static string deserialization_failed {
            get {
                return ResourceManager.GetString("deserialization_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The number of variables ({0}) differs from the number of format specifiers ({1}).
        /// </summary>
        public static string different_variables_and_specifiers {
            get {
                return ResourceManager.GetString("different_variables_and_specifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The directory &apos;{0}&apos; does not exist.
        /// </summary>
        public static string directory_not_found {
            get {
                return ResourceManager.GetString("directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Extensions cannot be loaded by script. Use configuration files instead..
        /// </summary>
        public static string dl_not_supported {
            get {
                return ResourceManager.GetString("dl_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Equivalence class cannot be endpoint of range (first endpoint here).
        /// </summary>
        public static string equivalence_class_at_first_endpoint_of_range {
            get {
                return ResourceManager.GetString("equivalence_class_at_first_endpoint_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Equivalence class cannot be an endpoint of a range (second endpoint here).
        /// </summary>
        public static string equivalence_class_at_second_endpoint_of_range {
            get {
                return ResourceManager.GetString("equivalence_class_at_second_endpoint_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error occured while closing the connection: {0}.
        /// </summary>
        public static string error_closing_connection {
            get {
                return ResourceManager.GetString("error_closing_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occured while starting process: {0}.
        /// </summary>
        public static string error_starting_process {
            get {
                return ResourceManager.GetString("error_starting_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occured while terminating process {0} (pid = {1}): {2}.
        /// </summary>
        public static string error_terminating_process {
            get {
                return ResourceManager.GetString("error_terminating_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occured while waiting for process exit: {0}.
        /// </summary>
        public static string error_waiting_for_process_exit {
            get {
                return ResourceManager.GetString("error_waiting_for_process_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field (column) of name &apos;{0}&apos; doesn&apos;t exist in the result.
        /// </summary>
        public static string field_not_exists {
            get {
                return ResourceManager.GetString("field_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to First endpoint of range cannot be a character class.
        /// </summary>
        public static string first_endpoint_character_class {
            get {
                return ResourceManager.GetString("first_endpoint_character_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Function not allowed in web server context.
        /// </summary>
        public static string function_disallowed_in_web_context {
            get {
                return ResourceManager.GetString("function_disallowed_in_web_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Header &apos;{0}&apos; not supported and has been ignored.
        /// </summary>
        public static string header_not_supported {
            get {
                return ResourceManager.GetString("header_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Headers has already been sent; modification of cookies or other HTTP headers are not allowed.
        /// </summary>
        public static string headers_has_been_sent {
            get {
                return ResourceManager.GetString("headers_has_been_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested host not responding.
        /// </summary>
        public static string host_not_responding {
            get {
                return ResourceManager.GetString("host_not_responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to HTTP request failed with message &apos;{0}&apos;.
        /// </summary>
        public static string http_request_failed {
            get {
                return ResourceManager.GetString("http_request_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Detected an illegal character in input string.
        /// </summary>
        public static string illegal_character {
            get {
                return ResourceManager.GetString("illegal_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: illegal hex digit &apos;{0}&apos;.
        /// </summary>
        public static string illegal_hex_digit {
            get {
                return ResourceManager.GetString("illegal_hex_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parse error on line {0}.
        /// </summary>
        public static string ini_parse_error {
            get {
                return ResourceManager.GetString("ini_parse_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid argument &apos;{0}&apos;.
        /// </summary>
        public static string invalid_argument {
            get {
                return ResourceManager.GetString("invalid_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid base64 encoded data.
        /// </summary>
        public static string invalid_base64_encoded_data {
            get {
                return ResourceManager.GetString("invalid_base64_encoded_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; is not a valid value for cache limiter.
        /// </summary>
        public static string invalid_cache_limiter {
            get {
                return ResourceManager.GetString("invalid_cache_limiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid calendar id &apos;{0}&apos;.
        /// </summary>
        public static string invalid_calendar {
            get {
                return ResourceManager.GetString("invalid_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid connection resource.
        /// </summary>
        public static string invalid_connection_resource {
            get {
                return ResourceManager.GetString("invalid_connection_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Supplied resource is not a valid Stream-Context resource.
        /// </summary>
        public static string invalid_context_resource {
            get {
                return ResourceManager.GetString("invalid_context_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid data encountered in the stream (bad back reference marker)..
        /// </summary>
        public static string invalid_data_bad_back_reference {
            get {
                return ResourceManager.GetString("invalid_data_bad_back_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid data encountered in the stream (bad length marker)..
        /// </summary>
        public static string invalid_data_bad_length {
            get {
                return ResourceManager.GetString("invalid_data_bad_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid data encountered in the stream (the specified data type is invalid in this context)..
        /// </summary>
        public static string invalid_data_bad_type {
            get {
                return ResourceManager.GetString("invalid_data_bad_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field index {0} is invalid for {1} resource #{2}.
        /// </summary>
        public static string invalid_data_result_field_index {
            get {
                return ResourceManager.GetString("invalid_data_result_field_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Row index {0} is invalid for {1} resource #{2}.
        /// </summary>
        public static string invalid_data_result_row_index {
            get {
                return ResourceManager.GetString("invalid_data_result_row_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Supplied resource is not a valid Directory listing resource.
        /// </summary>
        public static string invalid_directory_resource {
            get {
                return ResourceManager.GetString("invalid_directory_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid destination charser.
        /// </summary>
        public static string invalid_dst_charset {
            get {
                return ResourceManager.GetString("invalid_dst_charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email address &apos;{0}&apos; is not valid.
        /// </summary>
        public static string invalid_email_address {
            get {
                return ResourceManager.GetString("invalid_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; is not a valid handle qualifier.
        /// </summary>
        public static string invalid_handle_qualifier {
            get {
                return ResourceManager.GetString("invalid_handle_qualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Path &apos;{0}&apos; is invalid.
        /// </summary>
        public static string invalid_path {
            get {
                return ResourceManager.GetString("invalid_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid port number &apos;{0}&apos;.
        /// </summary>
        public static string invalid_port {
            get {
                return ResourceManager.GetString("invalid_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid process resource.
        /// </summary>
        public static string invalid_process_resource {
            get {
                return ResourceManager.GetString("invalid_process_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid query result resource.
        /// </summary>
        public static string invalid_result_resource {
            get {
                return ResourceManager.GetString("invalid_result_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid scan conversion character &quot;{0}&quot;.
        /// </summary>
        public static string invalid_scan_conversion_character {
            get {
                return ResourceManager.GetString("invalid_scan_conversion_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid session save path &apos;{0}&apos;..
        /// </summary>
        public static string invalid_session_save_path {
            get {
                return ResourceManager.GetString("invalid_session_save_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid source charser.
        /// </summary>
        public static string invalid_src_charset {
            get {
                return ResourceManager.GetString("invalid_src_charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid stored procedure resource.
        /// </summary>
        public static string invalid_stored_procedure_resource {
            get {
                return ResourceManager.GetString("invalid_stored_procedure_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid name of type.
        /// </summary>
        public static string invalid_type_name {
            get {
                return ResourceManager.GetString("invalid_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not a valid URL, unable to parse ({0}).
        /// </summary>
        public static string invalid_url {
            get {
                return ResourceManager.GetString("invalid_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The given parameter is not a valid uuencoded string.
        /// </summary>
        public static string invalid_uuencoded_string {
            get {
                return ResourceManager.GetString("invalid_uuencoded_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Supplied resource is not a valid XML Parser resource.
        /// </summary>
        public static string invalid_xmlresource {
            get {
                return ResourceManager.GetString("invalid_xmlresource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Limit is less than 1.
        /// </summary>
        public static string limit_less_than_one {
            get {
                return ResourceManager.GetString("limit_less_than_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ignoring unsupported pattern modifier &apos;{0}&apos; in perl regular expression.
        /// </summary>
        public static string modifier_not_supported {
            get {
                return ResourceManager.GetString("modifier_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ignoring unknown pattern modifier &apos;{0}&apos; in perl regular expression.
        /// </summary>
        public static string modifier_unknown {
            get {
                return ResourceManager.GetString("modifier_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pattern modifier &apos;{0}&apos; is ignored due to use of modifier &apos;{1}&apos; in perl regular expression.
        /// </summary>
        public static string modifiers_inconsistent {
            get {
                return ResourceManager.GetString("modifiers_inconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: multi-byte characters are not supported.
        /// </summary>
        public static string multibyte_chars_unsupported {
            get {
                return ResourceManager.GetString("multibyte_chars_unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be greater than or equal to 0.
        /// </summary>
        public static string must_be_positive {
            get {
                return ResourceManager.GetString("must_be_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can {0} only string and integer values.
        /// </summary>
        public static string neither_string_nor_integer_value {
            get {
                return ResourceManager.GetString("neither_string_nor_integer_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No prefix specified - possible security hazard.
        /// </summary>
        public static string no_prefix_security_hazard {
            get {
                return ResourceManager.GetString("no_prefix_security_hazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string no_prefix_specified {
            get {
                return ResourceManager.GetString("no_prefix_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: not enough arguments.
        /// </summary>
        public static string not_enought_arguments {
            get {
                return ResourceManager.GetString("not_enought_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: not enough characters in string.
        /// </summary>
        public static string not_enought_characters {
            get {
                return ResourceManager.GetString("not_enought_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: not enough input, need {1}, have {2}.
        /// </summary>
        public static string not_enought_input {
            get {
                return ResourceManager.GetString("not_enought_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to XML Parser contains not parsed data. Ensure to call &quot;xml_parse&quot; with is_final parameter set to &quot;true&quot;..
        /// </summary>
        public static string not_parsed_data_left {
            get {
                return ResourceManager.GetString("not_parsed_data_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of elements must be positive.
        /// </summary>
        public static string number_of_elements_not_positive {
            get {
                return ResourceManager.GetString("number_of_elements_not_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The number of items is {0} but it must be between 1 and array item count {1}.
        /// </summary>
        public static string number_of_items_not_between_one_and_item_count {
            get {
                return ResourceManager.GetString("number_of_items_not_between_one_and_item_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of repetitions must be non-negative.
        /// </summary>
        public static string number_of_repetitions_negative {
            get {
                return ResourceManager.GetString("number_of_repetitions_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Option &apos;{0}&apos; has already been registered..
        /// </summary>
        public static string option_already_registered {
            get {
                return ResourceManager.GetString("option_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; option missing.
        /// </summary>
        public static string option_missing {
            get {
                return ResourceManager.GetString("option_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Configuration option &apos;{0}&apos; is not supported.
        /// </summary>
        public static string option_not_supported {
            get {
                return ResourceManager.GetString("option_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Configuration option &apos;{0}&apos; cannot be set or restored since it is read only.
        /// </summary>
        public static string option_readonly {
            get {
                return ResourceManager.GetString("option_readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: outside of string.
        /// </summary>
        public static string outside_string {
            get {
                return ResourceManager.GetString("outside_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter &apos;{0}&apos; has already been bound.
        /// </summary>
        public static string parameter_already_bound {
            get {
                return ResourceManager.GetString("parameter_already_bound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parse error on position {0} near &apos;{1}&apos;.
        /// </summary>
        public static string parse_error {
            get {
                return ResourceManager.GetString("parse_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to PREG_PATTERN_ORDER and PREG_SET_ORDER flags are mutually exclusive.
        /// </summary>
        public static string preg_match_pattern_set_order {
            get {
                return ResourceManager.GetString("preg_match_pattern_set_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No ending delimiter &apos;{0}&apos; found.
        /// </summary>
        public static string preg_no_end_delimiter {
            get {
                return ResourceManager.GetString("preg_no_end_delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quantifier &apos;?&apos; following nothing (after &apos;(&apos;).
        /// </summary>
        public static string question_mark_folowing_nothing {
            get {
                return ResourceManager.GetString("question_mark_folowing_nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Range: first character code is greater than second.
        /// </summary>
        public static string range_first_character_greater {
            get {
                return ResourceManager.GetString("range_first_character_greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Range not allowed here (first endpoint may be illeagal).
        /// </summary>
        public static string range_not_allowed {
            get {
                return ResourceManager.GetString("range_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ranges cannot share an endpoint.
        /// </summary>
        public static string range_shared_endpoint {
            get {
                return ResourceManager.GetString("range_shared_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ranges for current page encoding are not supported.
        /// </summary>
        public static string ranges_not_supported {
            get {
                return ResourceManager.GetString("ranges_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Recursion detected.
        /// </summary>
        public static string recursion_detected {
            get {
                return ResourceManager.GetString("recursion_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Regular expression cannot end with &apos;(&apos;.
        /// </summary>
        public static string regexp_cannot_end_with_open_bracket {
            get {
                return ResourceManager.GetString("regexp_cannot_end_with_open_bracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Regular expression cannot end with &apos;\\&apos;.
        /// </summary>
        public static string regexp_cannot_end_with_two_backslashes {
            get {
                return ResourceManager.GetString("regexp_cannot_end_with_two_backslashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nothing to repeat - duplicate quantifier at offset {0} in matching part of regular expression..
        /// </summary>
        public static string regexp_duplicate_quantifier {
            get {
                return ResourceManager.GetString("regexp_duplicate_quantifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Empty regular expression.
        /// </summary>
        public static string regular_expression_empty {
            get {
                return ResourceManager.GetString("regular_expression_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Replacement cannot be an array if pattern is not an array.
        /// </summary>
        public static string replacement_array_pattern_not {
            get {
                return ResourceManager.GetString("replacement_array_pattern_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The segment length must be greater then zero.
        /// </summary>
        public static string segment_length_not_positive {
            get {
                return ResourceManager.GetString("segment_length_not_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to PhpFormatter does not support serialization binders..
        /// </summary>
        public static string serialization_binder_unsupported {
            get {
                return ResourceManager.GetString("serialization_binder_unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Serialization failed: {0}.
        /// </summary>
        public static string serialization_failed {
            get {
                return ResourceManager.GetString("serialization_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Serialization of type {0} is not supported by PhpFormatter..
        /// </summary>
        public static string serialization_unsupported_type {
            get {
                return ResourceManager.GetString("serialization_unsupported_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}::serialize() must return a string or NULL.
        /// </summary>
        public static string serialize_must_return_null_or_string {
            get {
                return ResourceManager.GetString("serialize_must_return_null_or_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Serializer &apos;{0}&apos; has already been registered..
        /// </summary>
        public static string serializer_already_registered {
            get {
                return ResourceManager.GetString("serializer_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Session doesn&apos;t not exist.
        /// </summary>
        public static string session_not_exists {
            get {
                return ResourceManager.GetString("session_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} should be specified.
        /// </summary>
        public static string should_be_specified {
            get {
                return ResourceManager.GetString("should_be_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of seconds must be greater than or equal to 0.
        /// </summary>
        public static string sleep_seconds_less_zero {
            get {
                return ResourceManager.GetString("sleep_seconds_less_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to From header was not specified..
        /// </summary>
        public static string smtp_sendmail_from_not_set {
            get {
                return ResourceManager.GetString("smtp_sendmail_from_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error connecting &apos;{0}&apos;: {0}.
        /// </summary>
        public static string socket_open_error {
            get {
                return ResourceManager.GetString("socket_open_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Connect timeout: {0} did not respond.
        /// </summary>
        public static string socket_open_timeout {
            get {
                return ResourceManager.GetString("socket_open_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument #{0} specifies a sorting flag which has already been specified for the array.
        /// </summary>
        public static string sorting_flag_already_specified {
            get {
                return ResourceManager.GetString("sorting_flag_already_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to PhpFormatter does not support streaming context..
        /// </summary>
        public static string streaming_context_unsupported {
            get {
                return ResourceManager.GetString("streaming_context_unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Length value {0} exceeds string length.
        /// </summary>
        public static string substr_count_length_exceeds {
            get {
                return ResourceManager.GetString("substr_count_length_exceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Offset value {0} exceeds string length.
        /// </summary>
        public static string substr_count_offset_exceeds {
            get {
                return ResourceManager.GetString("substr_count_offset_exceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Offset should be greater than or equal to 0.
        /// </summary>
        public static string substr_count_offset_zero {
            get {
                return ResourceManager.GetString("substr_count_offset_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Length should be greater than 0.
        /// </summary>
        public static string substr_count_zero_length {
            get {
                return ResourceManager.GetString("substr_count_zero_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to PhpFormatter does not support surrogate selectors..
        /// </summary>
        public static string surrogate_selector_unsupported {
            get {
                return ResourceManager.GetString("surrogate_selector_unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to String containg Unicode characters greater than &apos;\u0800&apos; are not supported.
        /// </summary>
        public static string too_big_unicode_character {
            get {
                return ResourceManager.GetString("too_big_unicode_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Too few arguments.
        /// </summary>
        public static string too_few_arguments {
            get {
                return ResourceManager.GetString("too_few_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  # Copyright (C) 1999-2003 Free Software Foundation, Inc.
        ///# This file is part of the GNU LIBICONV Library.
        ///#
        ///# The GNU LIBICONV Library is free software; you can redistribute it
        ///# and/or modify it under the terms of the GNU Library General Public
        ///# License as published by the Free Software Foundation; either version 2
        ///# of the License, or (at your option) any later version.
        ///#
        ///# The GNU LIBICONV Library is distributed in the hope that it will be
        ///# useful, but WITHOUT ANY WARRANTY; without even the im [rest of string was truncated]&quot;;.
        /// </summary>
        public static string translit {
            get {
                return ResourceManager.GetString("translit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unenclosed bracket expression.
        /// </summary>
        public static string unenclosed_bracket_expression {
            get {
                return ResourceManager.GetString("unenclosed_bracket_expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to expects parameter {0} to be {1}, {2} given.
        /// </summary>
        public static string unexpected_arg_given {
            get {
                return ResourceManager.GetString("unexpected_arg_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected character in the stream..
        /// </summary>
        public static string unexpected_character_in_stream {
            get {
                return ResourceManager.GetString("unexpected_character_in_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected end of stream..
        /// </summary>
        public static string unexpected_end_of_stream {
            get {
                return ResourceManager.GetString("unexpected_end_of_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Uninitialized string offset &apos;{0}&apos;.
        /// </summary>
        public static string uninitialized_string_offset {
            get {
                return ResourceManager.GetString("uninitialized_string_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown character class name.
        /// </summary>
        public static string unknown_character_class {
            get {
                return ResourceManager.GetString("unknown_character_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to File type not recognized.
        /// </summary>
        public static string unknown_file_type {
            get {
                return ResourceManager.GetString("unknown_file_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type &apos;{0}&apos;: unknown format code.
        /// </summary>
        public static string unknown_format_code {
            get {
                return ResourceManager.GetString("unknown_format_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Configuration option &apos;{0}&apos; is not known.
        /// </summary>
        public static string unknown_option {
            get {
                return ResourceManager.GetString("unknown_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Serializer &apos;{0}&apos; is unknown. It hasn&apos;t been registered by any loaded library.
        /// </summary>
        public static string unknown_serializer {
            get {
                return ResourceManager.GetString("unknown_serializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown time zone &apos;{0}&apos;.
        /// </summary>
        public static string unknown_timezone {
            get {
                return ResourceManager.GetString("unknown_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown time zone &apos;{0}&apos; specified by &apos;TZ&apos; environment variable.
        /// </summary>
        public static string unknown_timezone_env {
            get {
                return ResourceManager.GetString("unknown_timezone_env", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unmatched [ in format string.
        /// </summary>
        public static string unmathed_format_bracket {
            get {
                return ResourceManager.GetString("unmathed_format_bracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} unused arguments.
        /// </summary>
        public static string unused_arguments {
            get {
                return ResourceManager.GetString("unused_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User session handler operation &apos;{0}&apos; failed (sid = &apos;{1}&apos;, save_path = &apos;{2}&apos;).
        /// </summary>
        public static string user_session_handler_failed {
            get {
                return ResourceManager.GetString("user_session_handler_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Using system time zone settings which may be inaccurate (&apos;{0}&apos; zone selected).
        /// </summary>
        public static string using_implicit_timezone {
            get {
                return ResourceManager.GetString("using_implicit_timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string web_server_not_available {
            get {
                return ResourceManager.GetString("web_server_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!-- document downloaded from http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml --&gt;
        ///&lt;supplementalData&gt;
        ///	&lt;windowsZones&gt;
        ///		&lt;mapTimezones otherVersion=&quot;07dc0000&quot; typeVersion=&quot;2012a&quot;&gt;
        ///
        ///			&lt;!-- (UTC-12:00) International Date Line West --&gt;
        ///			&lt;mapZone other=&quot;Dateline Standard Time&quot; territory=&quot;001&quot; type=&quot;Etc/GMT+12&quot;/&gt;
        ///			&lt;mapZone other=&quot;Dateline Standard Time&quot; territory=&quot;ZZ&quot; type=&quot;Etc/GMT+12&quot;/&gt;
        ///
        ///			&lt;!-- (UTC-11:00) Coordinated Universal Time- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WindowsTZ {
            get {
                return ResourceManager.GetString("WindowsTZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Word boundary must be single bracket expression.
        /// </summary>
        public static string word_boundary_not_single_bracket_expr {
            get {
                return ResourceManager.GetString("word_boundary_not_single_bracket_expr", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The destination wrapper is different from the source one; use copy instead.
        /// </summary>
        public static string wrappers_must_match {
            get {
                return ResourceManager.GetString("wrappers_must_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Wrong charset &apos;{0}&apos;, conversion from &apos;{1}&apos; to &apos;{2}&apos; is not allowed.
        /// </summary>
        public static string wrong_charset {
            get {
                return ResourceManager.GetString("wrong_charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Zero is not a valid argument number.
        /// </summary>
        public static string zero_argument_invalid {
            get {
                return ResourceManager.GetString("zero_argument_invalid", resourceCulture);
            }
        }
    }
}
