//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peachpie.Library.Graphics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peachpie.Library.Graphics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affine array must have six elements.
        /// </summary>
        internal static string affine_array_number_of_params {
            get {
                return ResourceManager.GetString("affine_array_number_of_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string or invalid image.
        /// </summary>
        internal static string empty_string_or_invalid_image {
            get {
                return ResourceManager.GetString("empty_string_or_invalid_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found &apos;{0}&apos;.
        /// </summary>
        internal static string failed_to_open_http_stream {
            get {
                return ResourceManager.GetString("failed_to_open_http_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to open stream: No such file or directory &apos;{0}&apos;.
        /// </summary>
        internal static string failed_to_open_stream {
            get {
                return ResourceManager.GetString("failed_to_open_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not supported.
        /// </summary>
        internal static string file_not_supported {
            get {
                return ResourceManager.GetString("file_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename cannot be empty.
        /// </summary>
        internal static string filename_cannot_be_empty {
            get {
                return ResourceManager.GetString("filename_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplied argument is not a valid Image resource.
        /// </summary>
        internal static string image_resource_not_valid {
            get {
                return ResourceManager.GetString("image_resource_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid font filename &apos;{0}&apos;.
        /// </summary>
        internal static string invalid_font_filename {
            get {
                return ResourceManager.GetString("invalid_font_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image dimensions.
        /// </summary>
        internal static string invalid_image_dimensions {
            get {
                return ResourceManager.GetString("invalid_image_dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameter or parameters.
        /// </summary>
        internal static string missing_params {
            get {
                return ResourceManager.GetString("missing_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a positive number of points.
        /// </summary>
        internal static string must_be_positive_number_of_points {
            get {
                return ResourceManager.GetString("must_be_positive_number_of_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid PNG file.
        /// </summary>
        internal static string not_valid_png {
            get {
                return ResourceManager.GetString("not_valid_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG file corrupted by ASCII conversion.
        /// </summary>
        internal static string png_corrupted {
            get {
                return ResourceManager.GetString("png_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read error!.
        /// </summary>
        internal static string read_error {
            get {
                return ResourceManager.GetString("read_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file &apos;{0}&apos;.
        /// </summary>
        internal static string unable_to_open_file {
            get {
                return ResourceManager.GetString("unable_to_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type of one or more parameters.
        /// </summary>
        internal static string wrong_type {
            get {
                return ResourceManager.GetString("wrong_type", resourceCulture);
            }
        }
    }
}
