//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peachpie.Library.XmlDom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peachpie.Library.XmlDom.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document fragment is empty.
        /// </summary>
        internal static string DocumentFragmentEmpty {
            get {
                return ResourceManager.GetString("DocumentFragmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inuse Attribute Error.
        /// </summary>
        internal static string ErrorAttributeInUse {
            get {
                return ResourceManager.GetString("ErrorAttributeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchy Request Error.
        /// </summary>
        internal static string ErrorBadHierarchy {
            get {
                return ResourceManager.GetString("ErrorBadHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Allowed Error.
        /// </summary>
        internal static string ErrorDataNotAllowed {
            get {
                return ResourceManager.GetString("ErrorDataNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Modification Allowed Error.
        /// </summary>
        internal static string ErrorDomModificationNotAllowed {
            get {
                return ResourceManager.GetString("ErrorDomModificationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Size Error.
        /// </summary>
        internal static string ErrorIndexOutOfBounds {
            get {
                return ResourceManager.GetString("ErrorIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Access Error.
        /// </summary>
        internal static string ErrorInvalidAccess {
            get {
                return ResourceManager.GetString("ErrorInvalidAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Character Error.
        /// </summary>
        internal static string ErrorInvalidCharacter {
            get {
                return ResourceManager.GetString("ErrorInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid State Error.
        /// </summary>
        internal static string ErrorInvalidState {
            get {
                return ResourceManager.GetString("ErrorInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Modification Error.
        /// </summary>
        internal static string ErrorModificationNotAllowed {
            get {
                return ResourceManager.GetString("ErrorModificationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace Error.
        /// </summary>
        internal static string ErrorNamespaceError {
            get {
                return ResourceManager.GetString("ErrorNamespaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found Error.
        /// </summary>
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported Error.
        /// </summary>
        internal static string ErrorNotSupported {
            get {
                return ResourceManager.GetString("ErrorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM String Size Error.
        /// </summary>
        internal static string ErrorStringTooLong {
            get {
                return ResourceManager.GetString("ErrorStringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error.
        /// </summary>
        internal static string ErrorSyntaxError {
            get {
                return ResourceManager.GetString("ErrorSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string ErrorValidationError {
            get {
                return ResourceManager.GetString("ErrorValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Document Error.
        /// </summary>
        internal static string ErrorWrongDocument {
            get {
                return ResourceManager.GetString("ErrorWrongDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXSLT support requires the Mvp.Xml library version 2.0 (assembly version 2.0.2158.1055) available at http://www.xmlmvp.org/. Insert Mvp.Xml.dll to GAC in order to enable EXSLT support..
        /// </summary>
        internal static string ExsltSupportMissing {
            get {
                return ResourceManager.GetString("ExsltSupportMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to call handler &apos;{0}()&apos;.
        /// </summary>
        internal static string HandlerNotAllowed {
            get {
                return ResourceManager.GetString("HandlerNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Document.
        /// </summary>
        internal static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid node type.
        /// </summary>
        internal static string InvalidNodeType {
            get {
                return ResourceManager.GetString("InvalidNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array key (must be string).
        /// </summary>
        internal static string InvalidParameterKey {
            get {
                return ResourceManager.GetString("InvalidParameterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state error.
        /// </summary>
        internal static string InvalidStateError {
            get {
                return ResourceManager.GetString("InvalidStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented.
        /// </summary>
        internal static string NotYetImplemented {
            get {
                return ResourceManager.GetString("NotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-load DTD schema validation is not supported.
        /// </summary>
        internal static string PostLoadDtdUnsupported {
            get {
                return ResourceManager.GetString("PostLoadDtdUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELAX NG schema validation is not supported.
        /// </summary>
        internal static string RelaxNGUnsupported {
            get {
                return ResourceManager.GetString("RelaxNGUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default/fixed value nodes creation during XSD schema validation is not supported.
        /// </summary>
        internal static string SchemaCreateUnsupported {
            get {
                return ResourceManager.GetString("SchemaCreateUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign to an array of nodes (duplicate subnodes of name &apos;{0}&apos; detected).
        /// </summary>
        internal static string SimpleXmlAssignmentToDuplicateNodes {
            get {
                return ResourceManager.GetString("SimpleXmlAssignmentToDuplicateNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The imported node must be associated with an XML document.
        /// </summary>
        internal static string SimpleXmlImportNotAssociated {
            get {
                return ResourceManager.GetString("SimpleXmlImportNotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; is not derived from SimpleXMLElement..
        /// </summary>
        internal static string SimpleXmlInvalidClassName {
            get {
                return ResourceManager.GetString("SimpleXmlInvalidClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid node type. Only instances of DOMElement and DOMDocument (contaning the root element) can be imported.
        /// </summary>
        internal static string SimpleXmlInvalidNodeToImport {
            get {
                return ResourceManager.GetString("SimpleXmlInvalidNodeToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperation with the SimpleXML extension is not implemented.
        /// </summary>
        internal static string SimpleXmlNotImplemented {
            get {
                return ResourceManager.GetString("SimpleXmlNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to assign complex types to nodes.
        /// </summary>
        internal static string SimpleXmlUnsupportedWriteConversion {
            get {
                return ResourceManager.GetString("SimpleXmlUnsupportedWriteConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDATA not allowed in this context!.
        /// </summary>
        internal static string XmlWritterCDataWrongContext {
            get {
                return ResourceManager.GetString("XmlWritterCDataWrongContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTD allowed only in prolog!.
        /// </summary>
        internal static string XmlWritterDtdInProlog {
            get {
                return ResourceManager.GetString("XmlWritterDtdInProlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining the number of bytes written to the current type of stream is not supported..
        /// </summary>
        internal static string XmlWritterNumberOfBytesUnsupported {
            get {
                return ResourceManager.GetString("XmlWritterNumberOfBytesUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system identifier needed!.
        /// </summary>
        internal static string XmlWritterSystemIdentifier {
            get {
                return ResourceManager.GetString("XmlWritterSystemIdentifier", resourceCulture);
            }
        }
    }
}
