name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        cache: true
    - name: Restore
      run: dotnet restore Peachpie.sln
    - name: Build
      run: dotnet build Peachpie.sln -c Release --no-restore -p:VersionSuffix=ghaction${{ github.run_number }}
    - name: Test
      run: dotnet test Peachpie.sln -c Release --no-build --verbosity normal
